/**
 * Stable machine-readable error codes returned in API error envelopes.
 * These are part of the public API contract — never rename or remove.
 */
export const ErrorCode = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  EMAIL_ACCOUNT_NOT_CONNECTED: "EMAIL_ACCOUNT_NOT_CONNECTED",
  OAUTH_TOKEN_EXPIRED: "OAUTH_TOKEN_EXPIRED",
  OAUTH_STATE_INVALID: "OAUTH_STATE_INVALID",
  PROVIDER_RATE_LIMITED: "PROVIDER_RATE_LIMITED",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  SYNC_FAILED: "SYNC_FAILED",
  ATTACHMENT_TOO_LARGE: "ATTACHMENT_TOO_LARGE",
  INVALID_ATTACHMENT: "INVALID_ATTACHMENT",
  RULE_EXECUTION_FAILED: "RULE_EXECUTION_FAILED",
  AI_SERVICE_UNAVAILABLE: "AI_SERVICE_UNAVAILABLE",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
